name: New System Request
description: Request the addition of a Lisp system to the ocicl repo
title: "[System Request]: "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to ocicl!
  - type: input
    id: project
    attributes:
      label: Name of the project
      description: Name of the project, which may not be the name of the system
      placeholder: ex. cl-myproject
    validations:
      required: true
  - type: input
    id: systems
    attributes:
      label: List of systems
      description: List of the systems provided by this project.
      placeholder: ex. mysystem myothersystem
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Tarball or git
      description: Is the upstream source a tarball or git repo?
      options:
        - git
        - tarball
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
      description: URL for the file or repo
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Git commit hash or release version
      description: For git repos, provide a commit hash.  For files, identify the verion (eg. 3.2.1)
    validations:
      required: true
